SELECT CITY, LENGTH(CITY) FROM STATION WHERE LENGTH(CITY) = (SELECT min(LENGTH(CITY)) FROM STATION) ORDER BY CITY LIMIT 1;
SELECT CITY, LENGTH(CITY) FROM STATION WHERE LENGTH(CITY) = (SELECT max(LENGTH(CITY)) FROM STATION) ORDER BY CITY LIMIT 1;
